# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='mention',
            name='note_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
        ),
    ]
