# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_adorable_kittens_height'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adorable_kittens',
            new_name='adorable_kitten',
        ),
    ]
