# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20170930_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adorable_kitten',
            name='height',
            field=models.FloatField(max_length=100),
        ),
    ]
