# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20171001_2254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='human',
            new_name='mention',
        ),
    ]
