# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20171001_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='cat_name',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='note',
            name='cat_pic',
        ),
        migrations.RemoveField(
            model_name='note',
            name='height',
        ),
    ]
