# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20171001_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mention',
            old_name='human_name',
            new_name='mention_name',
        ),
        migrations.RenameField(
            model_name='mention',
            old_name='cat_overlord',
            new_name='note_in',
        ),
        migrations.RemoveField(
            model_name='mention',
            name='height',
        ),
    ]
