# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adorable_kittens',
            name='height',
            field=models.FloatField(default=12.4, max_length=100),
            preserve_default=False,
        ),
    ]
