# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20170930_0929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='humans',
            new_name='human',
        ),
    ]
