# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_adorable_kitten_cat_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
