# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0010_auto_20171001_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='breed',
            new_name='title',
        ),
    ]
