# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0013_auto_20171001_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mention',
            name='is_favorite',
        ),
    ]
